//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ClienteMatricula.ProxyCursos {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CursoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class CursoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_CurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Cred_CurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Des_CurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Est_CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantProfesoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantSeccionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Cur {
            get {
                return this.Cod_CurField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_CurField, value) != true)) {
                    this.Cod_CurField = value;
                    this.RaisePropertyChanged("Cod_Cur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Cred_Cur {
            get {
                return this.Cred_CurField;
            }
            set {
                if ((this.Cred_CurField.Equals(value) != true)) {
                    this.Cred_CurField = value;
                    this.RaisePropertyChanged("Cred_Cur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Des_Cur {
            get {
                return this.Des_CurField;
            }
            set {
                if ((object.ReferenceEquals(this.Des_CurField, value) != true)) {
                    this.Des_CurField = value;
                    this.RaisePropertyChanged("Des_Cur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Est_Curso {
            get {
                return this.Est_CursoField;
            }
            set {
                if ((this.Est_CursoField.Equals(value) != true)) {
                    this.Est_CursoField = value;
                    this.RaisePropertyChanged("Est_Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Reg {
            get {
                return this.Fec_RegField;
            }
            set {
                if ((this.Fec_RegField.Equals(value) != true)) {
                    this.Fec_RegField = value;
                    this.RaisePropertyChanged("Fec_Reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Reg {
            get {
                return this.Usu_RegField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegField, value) != true)) {
                    this.Usu_RegField = value;
                    this.RaisePropertyChanged("Usu_Reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantProfesores {
            get {
                return this.cantProfesoresField;
            }
            set {
                if ((this.cantProfesoresField.Equals(value) != true)) {
                    this.cantProfesoresField = value;
                    this.RaisePropertyChanged("cantProfesores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantSecciones {
            get {
                return this.cantSeccionesField;
            }
            set {
                if ((this.cantSeccionesField.Equals(value) != true)) {
                    this.cantSeccionesField = value;
                    this.RaisePropertyChanged("cantSecciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCursos.IServicioCursos")]
    public interface IServicioCursos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ActualizarCurso", ReplyAction="http://tempuri.org/IServicioCursos/ActualizarCursoResponse")]
        bool ActualizarCurso(MVC_ClienteMatricula.ProxyCursos.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ActualizarCurso", ReplyAction="http://tempuri.org/IServicioCursos/ActualizarCursoResponse")]
        System.Threading.Tasks.Task<bool> ActualizarCursoAsync(MVC_ClienteMatricula.ProxyCursos.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ConsultarCurso", ReplyAction="http://tempuri.org/IServicioCursos/ConsultarCursoResponse")]
        MVC_ClienteMatricula.ProxyCursos.CursoDC ConsultarCurso(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ConsultarCurso", ReplyAction="http://tempuri.org/IServicioCursos/ConsultarCursoResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyCursos.CursoDC> ConsultarCursoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/EliminarCurso", ReplyAction="http://tempuri.org/IServicioCursos/EliminarCursoResponse")]
        bool EliminarCurso(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/EliminarCurso", ReplyAction="http://tempuri.org/IServicioCursos/EliminarCursoResponse")]
        System.Threading.Tasks.Task<bool> EliminarCursoAsync(string codigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/InsertarCurso", ReplyAction="http://tempuri.org/IServicioCursos/InsertarCursoResponse")]
        bool InsertarCurso(MVC_ClienteMatricula.ProxyCursos.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/InsertarCurso", ReplyAction="http://tempuri.org/IServicioCursos/InsertarCursoResponse")]
        System.Threading.Tasks.Task<bool> InsertarCursoAsync(MVC_ClienteMatricula.ProxyCursos.CursoDC objCursoDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ListarCurso", ReplyAction="http://tempuri.org/IServicioCursos/ListarCursoResponse")]
        MVC_ClienteMatricula.ProxyCursos.CursoDC[] ListarCurso();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ListarCurso", ReplyAction="http://tempuri.org/IServicioCursos/ListarCursoResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyCursos.CursoDC[]> ListarCursoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ListarCurso2", ReplyAction="http://tempuri.org/IServicioCursos/ListarCurso2Response")]
        MVC_ClienteMatricula.ProxyCursos.CursoDC[] ListarCurso2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCursos/ListarCurso2", ReplyAction="http://tempuri.org/IServicioCursos/ListarCurso2Response")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyCursos.CursoDC[]> ListarCurso2Async();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCursosChannel : MVC_ClienteMatricula.ProxyCursos.IServicioCursos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCursosClient : System.ServiceModel.ClientBase<MVC_ClienteMatricula.ProxyCursos.IServicioCursos>, MVC_ClienteMatricula.ProxyCursos.IServicioCursos {
        
        public ServicioCursosClient() {
        }
        
        public ServicioCursosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCursosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCursosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ActualizarCurso(MVC_ClienteMatricula.ProxyCursos.CursoDC objCursoDC) {
            return base.Channel.ActualizarCurso(objCursoDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarCursoAsync(MVC_ClienteMatricula.ProxyCursos.CursoDC objCursoDC) {
            return base.Channel.ActualizarCursoAsync(objCursoDC);
        }
        
        public MVC_ClienteMatricula.ProxyCursos.CursoDC ConsultarCurso(string codigo) {
            return base.Channel.ConsultarCurso(codigo);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyCursos.CursoDC> ConsultarCursoAsync(string codigo) {
            return base.Channel.ConsultarCursoAsync(codigo);
        }
        
        public bool EliminarCurso(string codigo) {
            return base.Channel.EliminarCurso(codigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCursoAsync(string codigo) {
            return base.Channel.EliminarCursoAsync(codigo);
        }
        
        public bool InsertarCurso(MVC_ClienteMatricula.ProxyCursos.CursoDC objCursoDC) {
            return base.Channel.InsertarCurso(objCursoDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarCursoAsync(MVC_ClienteMatricula.ProxyCursos.CursoDC objCursoDC) {
            return base.Channel.InsertarCursoAsync(objCursoDC);
        }
        
        public MVC_ClienteMatricula.ProxyCursos.CursoDC[] ListarCurso() {
            return base.Channel.ListarCurso();
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyCursos.CursoDC[]> ListarCursoAsync() {
            return base.Channel.ListarCursoAsync();
        }
        
        public MVC_ClienteMatricula.ProxyCursos.CursoDC[] ListarCurso2() {
            return base.Channel.ListarCurso2();
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyCursos.CursoDC[]> ListarCurso2Async() {
            return base.Channel.ListarCurso2Async();
        }
    }
}
