//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Matriculas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DBMatricula2Entities : DbContext
    {
        public DBMatricula2Entities()
            : base("name=DBMatricula2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_Cursos> Tb_Cursos { get; set; }
        public virtual DbSet<Tb_Especialidad> Tb_Especialidad { get; set; }
        public virtual DbSet<Tb_Estudiantes> Tb_Estudiantes { get; set; }
        public virtual DbSet<Tb_Horario> Tb_Horario { get; set; }
        public virtual DbSet<Tb_Matricula> Tb_Matricula { get; set; }
        public virtual DbSet<Tb_Periodo> Tb_Periodo { get; set; }
        public virtual DbSet<Tb_Profesores> Tb_Profesores { get; set; }
        public virtual DbSet<Tb_Seccion> Tb_Seccion { get; set; }
        public virtual DbSet<Tb_Sede> Tb_Sede { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_Usuario> Tb_Usuario { get; set; }
    
        public virtual int usp_ActualizarCursos(string vcod, string vdes, Nullable<int> vcred, string vUsu_ult_mod, Nullable<bool> vEst_Cur)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vdesParameter = vdes != null ?
                new ObjectParameter("vdes", vdes) :
                new ObjectParameter("vdes", typeof(string));
    
            var vcredParameter = vcred.HasValue ?
                new ObjectParameter("vcred", vcred) :
                new ObjectParameter("vcred", typeof(int));
    
            var vUsu_ult_modParameter = vUsu_ult_mod != null ?
                new ObjectParameter("vUsu_ult_mod", vUsu_ult_mod) :
                new ObjectParameter("vUsu_ult_mod", typeof(string));
    
            var vEst_CurParameter = vEst_Cur.HasValue ?
                new ObjectParameter("vEst_Cur", vEst_Cur) :
                new ObjectParameter("vEst_Cur", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarCursos", vcodParameter, vdesParameter, vcredParameter, vUsu_ult_modParameter, vEst_CurParameter);
        }
    
        public virtual int usp_ActualizarEstudiantes(string vcod, string vnom, string vape, string vtel, string vemail, string vId_Ubi, byte[] vfoto, string vdir, Nullable<System.DateTime> vFec_Nac, string vdni, string vUsu_ult_mod, Nullable<bool> vEst_Est)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vtelParameter = vtel != null ?
                new ObjectParameter("vtel", vtel) :
                new ObjectParameter("vtel", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vId_UbiParameter = vId_Ubi != null ?
                new ObjectParameter("vId_Ubi", vId_Ubi) :
                new ObjectParameter("vId_Ubi", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vFec_NacParameter = vFec_Nac.HasValue ?
                new ObjectParameter("vFec_Nac", vFec_Nac) :
                new ObjectParameter("vFec_Nac", typeof(System.DateTime));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vUsu_ult_modParameter = vUsu_ult_mod != null ?
                new ObjectParameter("vUsu_ult_mod", vUsu_ult_mod) :
                new ObjectParameter("vUsu_ult_mod", typeof(string));
    
            var vEst_EstParameter = vEst_Est.HasValue ?
                new ObjectParameter("vEst_Est", vEst_Est) :
                new ObjectParameter("vEst_Est", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarEstudiantes", vcodParameter, vnomParameter, vapeParameter, vtelParameter, vemailParameter, vId_UbiParameter, vfotoParameter, vdirParameter, vFec_NacParameter, vdniParameter, vUsu_ult_modParameter, vEst_EstParameter);
        }
    
        public virtual int usp_ActualizarProfesor(string vcod, string vnom, string vape, byte[] vfoto, string vdir, string vemail, Nullable<System.DateTime> vFec_Nac, string vdni, string vCod_Espc, string vId_Ubi, string vUsu_Ult_Mod, Nullable<bool> vEst)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vFec_NacParameter = vFec_Nac.HasValue ?
                new ObjectParameter("vFec_Nac", vFec_Nac) :
                new ObjectParameter("vFec_Nac", typeof(System.DateTime));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vCod_EspcParameter = vCod_Espc != null ?
                new ObjectParameter("vCod_Espc", vCod_Espc) :
                new ObjectParameter("vCod_Espc", typeof(string));
    
            var vId_UbiParameter = vId_Ubi != null ?
                new ObjectParameter("vId_Ubi", vId_Ubi) :
                new ObjectParameter("vId_Ubi", typeof(string));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            var vEstParameter = vEst.HasValue ?
                new ObjectParameter("vEst", vEst) :
                new ObjectParameter("vEst", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarProfesor", vcodParameter, vnomParameter, vapeParameter, vfotoParameter, vdirParameter, vemailParameter, vFec_NacParameter, vdniParameter, vCod_EspcParameter, vId_UbiParameter, vUsu_Ult_ModParameter, vEstParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarCursos_Result> usp_ConsultarCursos(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarCursos_Result>("usp_ConsultarCursos", vcodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarEstudiantes_Result> usp_ConsultarEstudiantes(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarEstudiantes_Result>("usp_ConsultarEstudiantes", vcodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarProfesor_Result> usp_ConsultarProfesor(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarProfesor_Result>("usp_ConsultarProfesor", vcodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultartCursos_Result> usp_ConsultartCursos(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultartCursos_Result>("usp_ConsultartCursos", vcodParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarUsuario_Result> usp_ConsultarUsuario(string login_Usu)
        {
            var login_UsuParameter = login_Usu != null ?
                new ObjectParameter("Login_Usu", login_Usu) :
                new ObjectParameter("Login_Usu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarUsuario_Result>("usp_ConsultarUsuario", login_UsuParameter);
        }
    
        public virtual int usp_EliminarCursos(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarCursos", vcodParameter);
        }
    
        public virtual int usp_EliminarEstudiante(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarEstudiante", vcodParameter);
        }
    
        public virtual int usp_EliminarProfesor(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarProfesor", vcodParameter);
        }
    
        public virtual ObjectResult<usp_Especialidad_Descripcion_Result> usp_Especialidad_Descripcion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Especialidad_Descripcion_Result>("usp_Especialidad_Descripcion");
        }
    
        public virtual int usp_InsertarCursos(string vdes, Nullable<int> vcred, string vUsu_Registro, Nullable<bool> vEst_Cur)
        {
            var vdesParameter = vdes != null ?
                new ObjectParameter("vdes", vdes) :
                new ObjectParameter("vdes", typeof(string));
    
            var vcredParameter = vcred.HasValue ?
                new ObjectParameter("vcred", vcred) :
                new ObjectParameter("vcred", typeof(int));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            var vEst_CurParameter = vEst_Cur.HasValue ?
                new ObjectParameter("vEst_Cur", vEst_Cur) :
                new ObjectParameter("vEst_Cur", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarCursos", vdesParameter, vcredParameter, vUsu_RegistroParameter, vEst_CurParameter);
        }
    
        public virtual int usp_InsertarEstudiantes(string vnom, string vape, string vtel, string vemail, string vId_Ubi, byte[] vfoto, string vdir, string vFec_Nac, string vdni, string vUsu_Registro, Nullable<bool> vEst_Est)
        {
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vtelParameter = vtel != null ?
                new ObjectParameter("vtel", vtel) :
                new ObjectParameter("vtel", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vId_UbiParameter = vId_Ubi != null ?
                new ObjectParameter("vId_Ubi", vId_Ubi) :
                new ObjectParameter("vId_Ubi", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vFec_NacParameter = vFec_Nac != null ?
                new ObjectParameter("vFec_Nac", vFec_Nac) :
                new ObjectParameter("vFec_Nac", typeof(string));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vUsu_RegistroParameter = vUsu_Registro != null ?
                new ObjectParameter("vUsu_Registro", vUsu_Registro) :
                new ObjectParameter("vUsu_Registro", typeof(string));
    
            var vEst_EstParameter = vEst_Est.HasValue ?
                new ObjectParameter("vEst_Est", vEst_Est) :
                new ObjectParameter("vEst_Est", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarEstudiantes", vnomParameter, vapeParameter, vtelParameter, vemailParameter, vId_UbiParameter, vfotoParameter, vdirParameter, vFec_NacParameter, vdniParameter, vUsu_RegistroParameter, vEst_EstParameter);
        }
    
        public virtual int usp_InsertarProfesor(string vnom, string vape, byte[] vfoto, string vdir, string vemail, Nullable<System.DateTime> vFec_Nac, string vdni, string vCod_Espc, string vId_Ubi, string vUsu_Reg, Nullable<bool> vEst)
        {
            var vnomParameter = vnom != null ?
                new ObjectParameter("vnom", vnom) :
                new ObjectParameter("vnom", typeof(string));
    
            var vapeParameter = vape != null ?
                new ObjectParameter("vape", vape) :
                new ObjectParameter("vape", typeof(string));
    
            var vfotoParameter = vfoto != null ?
                new ObjectParameter("vfoto", vfoto) :
                new ObjectParameter("vfoto", typeof(byte[]));
    
            var vdirParameter = vdir != null ?
                new ObjectParameter("vdir", vdir) :
                new ObjectParameter("vdir", typeof(string));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vFec_NacParameter = vFec_Nac.HasValue ?
                new ObjectParameter("vFec_Nac", vFec_Nac) :
                new ObjectParameter("vFec_Nac", typeof(System.DateTime));
    
            var vdniParameter = vdni != null ?
                new ObjectParameter("vdni", vdni) :
                new ObjectParameter("vdni", typeof(string));
    
            var vCod_EspcParameter = vCod_Espc != null ?
                new ObjectParameter("vCod_Espc", vCod_Espc) :
                new ObjectParameter("vCod_Espc", typeof(string));
    
            var vId_UbiParameter = vId_Ubi != null ?
                new ObjectParameter("vId_Ubi", vId_Ubi) :
                new ObjectParameter("vId_Ubi", typeof(string));
    
            var vUsu_RegParameter = vUsu_Reg != null ?
                new ObjectParameter("vUsu_Reg", vUsu_Reg) :
                new ObjectParameter("vUsu_Reg", typeof(string));
    
            var vEstParameter = vEst.HasValue ?
                new ObjectParameter("vEst", vEst) :
                new ObjectParameter("vEst", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarProfesor", vnomParameter, vapeParameter, vfotoParameter, vdirParameter, vemailParameter, vFec_NacParameter, vdniParameter, vCod_EspcParameter, vId_UbiParameter, vUsu_RegParameter, vEstParameter);
        }
    
        public virtual ObjectResult<usp_ListarCursos_Result> usp_ListarCursos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarCursos_Result>("usp_ListarCursos");
        }
    
        public virtual ObjectResult<usp_ListarEstudiantes_Result> usp_ListarEstudiantes()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarEstudiantes_Result>("usp_ListarEstudiantes");
        }
    
        public virtual ObjectResult<usp_ListarProfesor_Result> usp_ListarProfesor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarProfesor_Result>("usp_ListarProfesor");
        }
    
        public virtual ObjectResult<usp_Ubigeo_Departamentos_Result> usp_Ubigeo_Departamentos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_Departamentos_Result>("usp_Ubigeo_Departamentos");
        }
    
        public virtual ObjectResult<usp_Ubigeo_DistritosProvinciaDepartamento_Result> usp_Ubigeo_DistritosProvinciaDepartamento(string idDepartamento, string idProvincia)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            var idProvinciaParameter = idProvincia != null ?
                new ObjectParameter("IdProvincia", idProvincia) :
                new ObjectParameter("IdProvincia", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_DistritosProvinciaDepartamento_Result>("usp_Ubigeo_DistritosProvinciaDepartamento", idDepartamentoParameter, idProvinciaParameter);
        }
    
        public virtual ObjectResult<usp_Ubigeo_ProvinciasDepartamento_Result> usp_Ubigeo_ProvinciasDepartamento(string idDepartamento)
        {
            var idDepartamentoParameter = idDepartamento != null ?
                new ObjectParameter("IdDepartamento", idDepartamento) :
                new ObjectParameter("IdDepartamento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_Ubigeo_ProvinciasDepartamento_Result>("usp_Ubigeo_ProvinciasDepartamento", idDepartamentoParameter);
        }
    
        public virtual int usp_ActualizarSeccion(string vcod, string vCod_Cur, string vCod_Hor, string vCod_Pro, string vCod_Sed, Nullable<bool> vModalidad, string vNum_Aula, Nullable<int> vCupo, string vUsu_Ult_Mod, Nullable<bool> vEst_Sec)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            var vCod_CurParameter = vCod_Cur != null ?
                new ObjectParameter("vCod_Cur", vCod_Cur) :
                new ObjectParameter("vCod_Cur", typeof(string));
    
            var vCod_HorParameter = vCod_Hor != null ?
                new ObjectParameter("vCod_Hor", vCod_Hor) :
                new ObjectParameter("vCod_Hor", typeof(string));
    
            var vCod_ProParameter = vCod_Pro != null ?
                new ObjectParameter("vCod_Pro", vCod_Pro) :
                new ObjectParameter("vCod_Pro", typeof(string));
    
            var vCod_SedParameter = vCod_Sed != null ?
                new ObjectParameter("vCod_Sed", vCod_Sed) :
                new ObjectParameter("vCod_Sed", typeof(string));
    
            var vModalidadParameter = vModalidad.HasValue ?
                new ObjectParameter("vModalidad", vModalidad) :
                new ObjectParameter("vModalidad", typeof(bool));
    
            var vNum_AulaParameter = vNum_Aula != null ?
                new ObjectParameter("vNum_Aula", vNum_Aula) :
                new ObjectParameter("vNum_Aula", typeof(string));
    
            var vCupoParameter = vCupo.HasValue ?
                new ObjectParameter("vCupo", vCupo) :
                new ObjectParameter("vCupo", typeof(int));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            var vEst_SecParameter = vEst_Sec.HasValue ?
                new ObjectParameter("vEst_Sec", vEst_Sec) :
                new ObjectParameter("vEst_Sec", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_ActualizarSeccion", vcodParameter, vCod_CurParameter, vCod_HorParameter, vCod_ProParameter, vCod_SedParameter, vModalidadParameter, vNum_AulaParameter, vCupoParameter, vUsu_Ult_ModParameter, vEst_SecParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarSeccion_Result> usp_ConsultarSeccion(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarSeccion_Result>("usp_ConsultarSeccion", vcodParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> usp_DocentesxEspecialidad(string cod_esp)
        {
            var cod_espParameter = cod_esp != null ?
                new ObjectParameter("cod_esp", cod_esp) :
                new ObjectParameter("cod_esp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("usp_DocentesxEspecialidad", cod_espParameter);
        }
    
        public virtual int usp_EliminarSeccion(string vcod)
        {
            var vcodParameter = vcod != null ?
                new ObjectParameter("vcod", vcod) :
                new ObjectParameter("vcod", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_EliminarSeccion", vcodParameter);
        }
    
        public virtual int usp_InsertarSeccion(string vCod_Cur, string vCod_Hor, string vCod_Pro, string vCod_Sed, Nullable<bool> vModalidad, string vNum_Aula, Nullable<int> vcupo, string vUsu_Ult, string vUsu_Ult_Mod, Nullable<bool> vEst_Sec)
        {
            var vCod_CurParameter = vCod_Cur != null ?
                new ObjectParameter("vCod_Cur", vCod_Cur) :
                new ObjectParameter("vCod_Cur", typeof(string));
    
            var vCod_HorParameter = vCod_Hor != null ?
                new ObjectParameter("vCod_Hor", vCod_Hor) :
                new ObjectParameter("vCod_Hor", typeof(string));
    
            var vCod_ProParameter = vCod_Pro != null ?
                new ObjectParameter("vCod_Pro", vCod_Pro) :
                new ObjectParameter("vCod_Pro", typeof(string));
    
            var vCod_SedParameter = vCod_Sed != null ?
                new ObjectParameter("vCod_Sed", vCod_Sed) :
                new ObjectParameter("vCod_Sed", typeof(string));
    
            var vModalidadParameter = vModalidad.HasValue ?
                new ObjectParameter("vModalidad", vModalidad) :
                new ObjectParameter("vModalidad", typeof(bool));
    
            var vNum_AulaParameter = vNum_Aula != null ?
                new ObjectParameter("vNum_Aula", vNum_Aula) :
                new ObjectParameter("vNum_Aula", typeof(string));
    
            var vcupoParameter = vcupo.HasValue ?
                new ObjectParameter("vcupo", vcupo) :
                new ObjectParameter("vcupo", typeof(int));
    
            var vUsu_UltParameter = vUsu_Ult != null ?
                new ObjectParameter("vUsu_Ult", vUsu_Ult) :
                new ObjectParameter("vUsu_Ult", typeof(string));
    
            var vUsu_Ult_ModParameter = vUsu_Ult_Mod != null ?
                new ObjectParameter("vUsu_Ult_Mod", vUsu_Ult_Mod) :
                new ObjectParameter("vUsu_Ult_Mod", typeof(string));
    
            var vEst_SecParameter = vEst_Sec.HasValue ?
                new ObjectParameter("vEst_Sec", vEst_Sec) :
                new ObjectParameter("vEst_Sec", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_InsertarSeccion", vCod_CurParameter, vCod_HorParameter, vCod_ProParameter, vCod_SedParameter, vModalidadParameter, vNum_AulaParameter, vcupoParameter, vUsu_UltParameter, vUsu_Ult_ModParameter, vEst_SecParameter);
        }
    
        public virtual ObjectResult<usp_ListarSeccion_Result> usp_ListarSeccion()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarSeccion_Result>("usp_ListarSeccion");
        }
    
        public virtual ObjectResult<usp_ObtenerCantidadAlumnosPorPeriodo_Result> usp_ObtenerCantidadAlumnosPorPeriodo(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerCantidadAlumnosPorPeriodo_Result>("usp_ObtenerCantidadAlumnosPorPeriodo", periodoParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerCargaTrabajoProfesor_Result> usp_ObtenerCargaTrabajoProfesor(string periodo)
        {
            var periodoParameter = periodo != null ?
                new ObjectParameter("Periodo", periodo) :
                new ObjectParameter("Periodo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerCargaTrabajoProfesor_Result>("usp_ObtenerCargaTrabajoProfesor", periodoParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerProfesoresPorCurso_Result> usp_ObtenerProfesoresPorCurso(string cod_Cur)
        {
            var cod_CurParameter = cod_Cur != null ?
                new ObjectParameter("Cod_Cur", cod_Cur) :
                new ObjectParameter("Cod_Cur", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerProfesoresPorCurso_Result>("usp_ObtenerProfesoresPorCurso", cod_CurParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerProfesoresPorEspecialidad_Result> usp_ObtenerProfesoresPorEspecialidad(string cod_Esp)
        {
            var cod_EspParameter = cod_Esp != null ?
                new ObjectParameter("Cod_Esp", cod_Esp) :
                new ObjectParameter("Cod_Esp", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerProfesoresPorEspecialidad_Result>("usp_ObtenerProfesoresPorEspecialidad", cod_EspParameter);
        }
    
        public virtual ObjectResult<usp_ObtenerSeccionesPorCurso_Result> usp_ObtenerSeccionesPorCurso(string cod_Cur)
        {
            var cod_CurParameter = cod_Cur != null ?
                new ObjectParameter("Cod_Cur", cod_Cur) :
                new ObjectParameter("Cod_Cur", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ObtenerSeccionesPorCurso_Result>("usp_ObtenerSeccionesPorCurso", cod_CurParameter);
        }
    }
}
