//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Matriculas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Estudiantes
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Estudiantes()
        {
            this.Tb_Matricula = new HashSet<Tb_Matricula>();
        }
    
        public string Cod_Est { get; set; }
        public string Nom_Est { get; set; }
        public string Ape_Est { get; set; }
        public string Tel_Est { get; set; }
        public string Email_Est { get; set; }
        public string Id_Ubigeo { get; set; }
        public string direccion_Est { get; set; }
        public Nullable<System.DateTime> Fec_Nac_Est { get; set; }
        public string DNI_Pro { get; set; }
        public string Usu_Reg { get; set; }
        public Nullable<System.DateTime> Fec_Reg { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public Nullable<bool> Est_Est { get; set; }
        public byte[] Foto_Est { get; set; }
    
        public virtual Tb_Ubigeo Tb_Ubigeo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Matricula> Tb_Matricula { get; set; }
    }
}
