//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Matriculas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Horario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Horario()
        {
            this.Tb_Seccion = new HashSet<Tb_Seccion>();
        }
    
        public string Cod_Hor { get; set; }
        public string DiaSem_Hor { get; set; }
        public Nullable<System.TimeSpan> Ini_Hor { get; set; }
        public Nullable<System.TimeSpan> Fin_Hor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Seccion> Tb_Seccion { get; set; }
    }
}
