//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Matriculas
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_Seccion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tb_Seccion()
        {
            this.Tb_Matricula = new HashSet<Tb_Matricula>();
        }
    
        public string Id_Seccion { get; set; }
        public string Cod_Cur { get; set; }
        public string Cod_Hor { get; set; }
        public string Cod_Pro { get; set; }
        public string Cod_Sed { get; set; }
        public bool Modalidad { get; set; }
        public string Num_Aula { get; set; }
        public Nullable<int> cupo { get; set; }
        public string Usu_Reg { get; set; }
        public Nullable<System.DateTime> Fec_Reg { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public Nullable<bool> Est_Sec { get; set; }
    
        public virtual Tb_Cursos Tb_Cursos { get; set; }
        public virtual Tb_Horario Tb_Horario { get; set; }
        public virtual Tb_Profesores Tb_Profesores { get; set; }
        public virtual Tb_Sede Tb_Sede { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tb_Matricula> Tb_Matricula { get; set; }
    }
}
