//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ClienteMatricula.ProxySecciones {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SeccionDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class SeccionDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_CurField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_HorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_SedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Est_SecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_SeccionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short ModalidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Num_AulaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SedeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short cupoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Cur {
            get {
                return this.Cod_CurField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_CurField, value) != true)) {
                    this.Cod_CurField = value;
                    this.RaisePropertyChanged("Cod_Cur");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Curso {
            get {
                return this.Cod_CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_CursoField, value) != true)) {
                    this.Cod_CursoField = value;
                    this.RaisePropertyChanged("Cod_Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Hor {
            get {
                return this.Cod_HorField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_HorField, value) != true)) {
                    this.Cod_HorField = value;
                    this.RaisePropertyChanged("Cod_Hor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Pro {
            get {
                return this.Cod_ProField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_ProField, value) != true)) {
                    this.Cod_ProField = value;
                    this.RaisePropertyChanged("Cod_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Sed {
            get {
                return this.Cod_SedField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_SedField, value) != true)) {
                    this.Cod_SedField = value;
                    this.RaisePropertyChanged("Cod_Sed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Est_Sec {
            get {
                return this.Est_SecField;
            }
            set {
                if ((this.Est_SecField.Equals(value) != true)) {
                    this.Est_SecField = value;
                    this.RaisePropertyChanged("Est_Sec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Reg {
            get {
                return this.Fec_RegField;
            }
            set {
                if ((this.Fec_RegField.Equals(value) != true)) {
                    this.Fec_RegField = value;
                    this.RaisePropertyChanged("Fec_Reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HorarioField, value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Seccion {
            get {
                return this.Id_SeccionField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_SeccionField, value) != true)) {
                    this.Id_SeccionField = value;
                    this.RaisePropertyChanged("Id_Seccion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Modalidad {
            get {
                return this.ModalidadField;
            }
            set {
                if ((this.ModalidadField.Equals(value) != true)) {
                    this.ModalidadField = value;
                    this.RaisePropertyChanged("Modalidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Curso {
            get {
                return this.Nom_CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_CursoField, value) != true)) {
                    this.Nom_CursoField = value;
                    this.RaisePropertyChanged("Nom_Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompletoProfesor {
            get {
                return this.NombreCompletoProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoProfesorField, value) != true)) {
                    this.NombreCompletoProfesorField = value;
                    this.RaisePropertyChanged("NombreCompletoProfesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Num_Aula {
            get {
                return this.Num_AulaField;
            }
            set {
                if ((object.ReferenceEquals(this.Num_AulaField, value) != true)) {
                    this.Num_AulaField = value;
                    this.RaisePropertyChanged("Num_Aula");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sede {
            get {
                return this.SedeField;
            }
            set {
                if ((object.ReferenceEquals(this.SedeField, value) != true)) {
                    this.SedeField = value;
                    this.RaisePropertyChanged("Sede");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Reg {
            get {
                return this.Usu_RegField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegField, value) != true)) {
                    this.Usu_RegField = value;
                    this.RaisePropertyChanged("Usu_Reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short cupo {
            get {
                return this.cupoField;
            }
            set {
                if ((this.cupoField.Equals(value) != true)) {
                    this.cupoField = value;
                    this.RaisePropertyChanged("cupo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxySecciones.IServicioSecciones")]
    public interface IServicioSecciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ActualizarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/ActualizarSeccionResponse")]
        bool ActualizarSeccion(MVC_ClienteMatricula.ProxySecciones.SeccionDC objSeccionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ActualizarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/ActualizarSeccionResponse")]
        System.Threading.Tasks.Task<bool> ActualizarSeccionAsync(MVC_ClienteMatricula.ProxySecciones.SeccionDC objSeccionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ConsultarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/ConsultarSeccionResponse")]
        MVC_ClienteMatricula.ProxySecciones.SeccionDC ConsultarSeccion(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ConsultarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/ConsultarSeccionResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC> ConsultarSeccionAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/EliminarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/EliminarSeccionResponse")]
        bool EliminarSeccion(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/EliminarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/EliminarSeccionResponse")]
        System.Threading.Tasks.Task<bool> EliminarSeccionAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/InsertarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/InsertarSeccionResponse")]
        bool InsertarSeccion(MVC_ClienteMatricula.ProxySecciones.SeccionDC objSeccionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/InsertarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/InsertarSeccionResponse")]
        System.Threading.Tasks.Task<bool> InsertarSeccionAsync(MVC_ClienteMatricula.ProxySecciones.SeccionDC objSeccionDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ListarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/ListarSeccionResponse")]
        MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ListarSeccion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ListarSeccion", ReplyAction="http://tempuri.org/IServicioSecciones/ListarSeccionResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ListarSeccionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ListarSeccion2", ReplyAction="http://tempuri.org/IServicioSecciones/ListarSeccion2Response")]
        MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ListarSeccion2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ListarSeccion2", ReplyAction="http://tempuri.org/IServicioSecciones/ListarSeccion2Response")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ListarSeccion2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ListarSeccionCurso", ReplyAction="http://tempuri.org/IServicioSecciones/ListarSeccionCursoResponse")]
        MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ListarSeccionCurso(string strCodCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ListarSeccionCurso", ReplyAction="http://tempuri.org/IServicioSecciones/ListarSeccionCursoResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ListarSeccionCursoAsync(string strCodCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ListarSeccionProfesor", ReplyAction="http://tempuri.org/IServicioSecciones/ListarSeccionProfesorResponse")]
        MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ListarSeccionProfesor(string strCodProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ListarSeccionProfesor", ReplyAction="http://tempuri.org/IServicioSecciones/ListarSeccionProfesorResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ListarSeccionProfesorAsync(string strCodProfesor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ObtenerSeccionesPorCurso", ReplyAction="http://tempuri.org/IServicioSecciones/ObtenerSeccionesPorCursoResponse")]
        MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ObtenerSeccionesPorCurso(string strCodCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSecciones/ObtenerSeccionesPorCurso", ReplyAction="http://tempuri.org/IServicioSecciones/ObtenerSeccionesPorCursoResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ObtenerSeccionesPorCursoAsync(string strCodCurso);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSeccionesChannel : MVC_ClienteMatricula.ProxySecciones.IServicioSecciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSeccionesClient : System.ServiceModel.ClientBase<MVC_ClienteMatricula.ProxySecciones.IServicioSecciones>, MVC_ClienteMatricula.ProxySecciones.IServicioSecciones {
        
        public ServicioSeccionesClient() {
        }
        
        public ServicioSeccionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSeccionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSeccionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSeccionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ActualizarSeccion(MVC_ClienteMatricula.ProxySecciones.SeccionDC objSeccionDC) {
            return base.Channel.ActualizarSeccion(objSeccionDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarSeccionAsync(MVC_ClienteMatricula.ProxySecciones.SeccionDC objSeccionDC) {
            return base.Channel.ActualizarSeccionAsync(objSeccionDC);
        }
        
        public MVC_ClienteMatricula.ProxySecciones.SeccionDC ConsultarSeccion(string strCodigo) {
            return base.Channel.ConsultarSeccion(strCodigo);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC> ConsultarSeccionAsync(string strCodigo) {
            return base.Channel.ConsultarSeccionAsync(strCodigo);
        }
        
        public bool EliminarSeccion(string strCodigo) {
            return base.Channel.EliminarSeccion(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarSeccionAsync(string strCodigo) {
            return base.Channel.EliminarSeccionAsync(strCodigo);
        }
        
        public bool InsertarSeccion(MVC_ClienteMatricula.ProxySecciones.SeccionDC objSeccionDC) {
            return base.Channel.InsertarSeccion(objSeccionDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarSeccionAsync(MVC_ClienteMatricula.ProxySecciones.SeccionDC objSeccionDC) {
            return base.Channel.InsertarSeccionAsync(objSeccionDC);
        }
        
        public MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ListarSeccion() {
            return base.Channel.ListarSeccion();
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ListarSeccionAsync() {
            return base.Channel.ListarSeccionAsync();
        }
        
        public MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ListarSeccion2() {
            return base.Channel.ListarSeccion2();
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ListarSeccion2Async() {
            return base.Channel.ListarSeccion2Async();
        }
        
        public MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ListarSeccionCurso(string strCodCurso) {
            return base.Channel.ListarSeccionCurso(strCodCurso);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ListarSeccionCursoAsync(string strCodCurso) {
            return base.Channel.ListarSeccionCursoAsync(strCodCurso);
        }
        
        public MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ListarSeccionProfesor(string strCodProfesor) {
            return base.Channel.ListarSeccionProfesor(strCodProfesor);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ListarSeccionProfesorAsync(string strCodProfesor) {
            return base.Channel.ListarSeccionProfesorAsync(strCodProfesor);
        }
        
        public MVC_ClienteMatricula.ProxySecciones.SeccionDC[] ObtenerSeccionesPorCurso(string strCodCurso) {
            return base.Channel.ObtenerSeccionesPorCurso(strCodCurso);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySecciones.SeccionDC[]> ObtenerSeccionesPorCursoAsync(string strCodCurso) {
            return base.Channel.ObtenerSeccionesPorCursoAsync(strCodCurso);
        }
    }
}
