//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ClienteMatricula.ProxyProfesores {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class ProfesorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_EspecField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DNI_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Direccion_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EspecialidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> Est_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Nac_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_RegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] Foto_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_CursoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_ProField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Numero_seccionesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PeriodoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Pro {
            get {
                return this.Ape_ProField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_ProField, value) != true)) {
                    this.Ape_ProField = value;
                    this.RaisePropertyChanged("Ape_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Curso {
            get {
                return this.Cod_CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_CursoField, value) != true)) {
                    this.Cod_CursoField = value;
                    this.RaisePropertyChanged("Cod_Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Espec {
            get {
                return this.Cod_EspecField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_EspecField, value) != true)) {
                    this.Cod_EspecField = value;
                    this.RaisePropertyChanged("Cod_Espec");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Pro {
            get {
                return this.Cod_ProField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_ProField, value) != true)) {
                    this.Cod_ProField = value;
                    this.RaisePropertyChanged("Cod_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DNI_Pro {
            get {
                return this.DNI_ProField;
            }
            set {
                if ((object.ReferenceEquals(this.DNI_ProField, value) != true)) {
                    this.DNI_ProField = value;
                    this.RaisePropertyChanged("DNI_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion_Pro {
            get {
                return this.Direccion_ProField;
            }
            set {
                if ((object.ReferenceEquals(this.Direccion_ProField, value) != true)) {
                    this.Direccion_ProField = value;
                    this.RaisePropertyChanged("Direccion_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_Pro {
            get {
                return this.Email_ProField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_ProField, value) != true)) {
                    this.Email_ProField = value;
                    this.RaisePropertyChanged("Email_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Especialidad {
            get {
                return this.EspecialidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EspecialidadField, value) != true)) {
                    this.EspecialidadField = value;
                    this.RaisePropertyChanged("Especialidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> Est_Pro {
            get {
                return this.Est_ProField;
            }
            set {
                if ((this.Est_ProField.Equals(value) != true)) {
                    this.Est_ProField = value;
                    this.RaisePropertyChanged("Est_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Nac_Pro {
            get {
                return this.Fec_Nac_ProField;
            }
            set {
                if ((this.Fec_Nac_ProField.Equals(value) != true)) {
                    this.Fec_Nac_ProField = value;
                    this.RaisePropertyChanged("Fec_Nac_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Reg {
            get {
                return this.Fec_RegField;
            }
            set {
                if ((this.Fec_RegField.Equals(value) != true)) {
                    this.Fec_RegField = value;
                    this.RaisePropertyChanged("Fec_Reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Foto_Pro {
            get {
                return this.Foto_ProField;
            }
            set {
                if ((object.ReferenceEquals(this.Foto_ProField, value) != true)) {
                    this.Foto_ProField = value;
                    this.RaisePropertyChanged("Foto_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Curso {
            get {
                return this.Nom_CursoField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_CursoField, value) != true)) {
                    this.Nom_CursoField = value;
                    this.RaisePropertyChanged("Nom_Curso");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_Pro {
            get {
                return this.Nom_ProField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_ProField, value) != true)) {
                    this.Nom_ProField = value;
                    this.RaisePropertyChanged("Nom_Pro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Numero_secciones {
            get {
                return this.Numero_seccionesField;
            }
            set {
                if ((this.Numero_seccionesField.Equals(value) != true)) {
                    this.Numero_seccionesField = value;
                    this.RaisePropertyChanged("Numero_secciones");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Periodo {
            get {
                return this.PeriodoField;
            }
            set {
                if ((object.ReferenceEquals(this.PeriodoField, value) != true)) {
                    this.PeriodoField = value;
                    this.RaisePropertyChanged("Periodo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Reg {
            get {
                return this.Usu_RegField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegField, value) != true)) {
                    this.Usu_RegField = value;
                    this.RaisePropertyChanged("Usu_Reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyProfesores.IServicioProfesores")]
    public interface IServicioProfesores {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/ActualizarProfesorResponse")]
        bool ActualizarProfesor(MVC_ClienteMatricula.ProxyProfesores.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/ActualizarProfesorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(MVC_ClienteMatricula.ProxyProfesores.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/ConsultarProfesorResponse")]
        MVC_ClienteMatricula.ProxyProfesores.ProfesorDC ConsultarProfesor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/ConsultarProfesorResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC> ConsultarProfesorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/EliminarProfesorResponse")]
        bool EliminarProfesor(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/EliminarProfesorResponse")]
        System.Threading.Tasks.Task<bool> EliminarProfesorAsync(string strCodigo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/InsertarProfesorResponse")]
        bool InsertarProfesor(MVC_ClienteMatricula.ProxyProfesores.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/InsertarProfesorResponse")]
        System.Threading.Tasks.Task<bool> InsertarProfesorAsync(MVC_ClienteMatricula.ProxyProfesores.ProfesorDC objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ListarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/ListarProfesorResponse")]
        MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ListarProfesor();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ListarProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/ListarProfesorResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ListarProfesorAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ListarProfesor2", ReplyAction="http://tempuri.org/IServicioProfesores/ListarProfesor2Response")]
        MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ListarProfesor2();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ListarProfesor2", ReplyAction="http://tempuri.org/IServicioProfesores/ListarProfesor2Response")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ListarProfesor2Async();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ListarProfesorEspecialidad", ReplyAction="http://tempuri.org/IServicioProfesores/ListarProfesorEspecialidadResponse")]
        MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ListarProfesorEspecialidad(string strCodEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ListarProfesorEspecialidad", ReplyAction="http://tempuri.org/IServicioProfesores/ListarProfesorEspecialidadResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ListarProfesorEspecialidadAsync(string strCodEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ListarProfesorCurso", ReplyAction="http://tempuri.org/IServicioProfesores/ListarProfesorCursoResponse")]
        MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ListarProfesorCurso(string strCodCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ListarProfesorCurso", ReplyAction="http://tempuri.org/IServicioProfesores/ListarProfesorCursoResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ListarProfesorCursoAsync(string strCodCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ObtenerCargaTrabajoProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/ObtenerCargaTrabajoProfesorResponse")]
        MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ObtenerCargaTrabajoProfesor(string periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ObtenerCargaTrabajoProfesor", ReplyAction="http://tempuri.org/IServicioProfesores/ObtenerCargaTrabajoProfesorResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ObtenerCargaTrabajoProfesorAsync(string periodo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ObtenerProfesoresPorCurso", ReplyAction="http://tempuri.org/IServicioProfesores/ObtenerProfesoresPorCursoResponse")]
        MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ObtenerProfesoresPorCurso(string strCodCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ObtenerProfesoresPorCurso", ReplyAction="http://tempuri.org/IServicioProfesores/ObtenerProfesoresPorCursoResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ObtenerProfesoresPorCursoAsync(string strCodCurso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ObtenerProfesoresPorEspecialidad", ReplyAction="http://tempuri.org/IServicioProfesores/ObtenerProfesoresPorEspecialidadResponse")]
        MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ObtenerProfesoresPorEspecialidad(string strCodEspecialidad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesores/ObtenerProfesoresPorEspecialidad", ReplyAction="http://tempuri.org/IServicioProfesores/ObtenerProfesoresPorEspecialidadResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ObtenerProfesoresPorEspecialidadAsync(string strCodEspecialidad);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioProfesoresChannel : MVC_ClienteMatricula.ProxyProfesores.IServicioProfesores, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProfesoresClient : System.ServiceModel.ClientBase<MVC_ClienteMatricula.ProxyProfesores.IServicioProfesores>, MVC_ClienteMatricula.ProxyProfesores.IServicioProfesores {
        
        public ServicioProfesoresClient() {
        }
        
        public ServicioProfesoresClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProfesoresClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProfesoresClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProfesoresClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ActualizarProfesor(MVC_ClienteMatricula.ProxyProfesores.ProfesorDC objProfesorDC) {
            return base.Channel.ActualizarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(MVC_ClienteMatricula.ProxyProfesores.ProfesorDC objProfesorDC) {
            return base.Channel.ActualizarProfesorAsync(objProfesorDC);
        }
        
        public MVC_ClienteMatricula.ProxyProfesores.ProfesorDC ConsultarProfesor(string strCodigo) {
            return base.Channel.ConsultarProfesor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC> ConsultarProfesorAsync(string strCodigo) {
            return base.Channel.ConsultarProfesorAsync(strCodigo);
        }
        
        public bool EliminarProfesor(string strCodigo) {
            return base.Channel.EliminarProfesor(strCodigo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProfesorAsync(string strCodigo) {
            return base.Channel.EliminarProfesorAsync(strCodigo);
        }
        
        public bool InsertarProfesor(MVC_ClienteMatricula.ProxyProfesores.ProfesorDC objProfesorDC) {
            return base.Channel.InsertarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarProfesorAsync(MVC_ClienteMatricula.ProxyProfesores.ProfesorDC objProfesorDC) {
            return base.Channel.InsertarProfesorAsync(objProfesorDC);
        }
        
        public MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ListarProfesor() {
            return base.Channel.ListarProfesor();
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ListarProfesorAsync() {
            return base.Channel.ListarProfesorAsync();
        }
        
        public MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ListarProfesor2() {
            return base.Channel.ListarProfesor2();
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ListarProfesor2Async() {
            return base.Channel.ListarProfesor2Async();
        }
        
        public MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ListarProfesorEspecialidad(string strCodEspecialidad) {
            return base.Channel.ListarProfesorEspecialidad(strCodEspecialidad);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ListarProfesorEspecialidadAsync(string strCodEspecialidad) {
            return base.Channel.ListarProfesorEspecialidadAsync(strCodEspecialidad);
        }
        
        public MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ListarProfesorCurso(string strCodCurso) {
            return base.Channel.ListarProfesorCurso(strCodCurso);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ListarProfesorCursoAsync(string strCodCurso) {
            return base.Channel.ListarProfesorCursoAsync(strCodCurso);
        }
        
        public MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ObtenerCargaTrabajoProfesor(string periodo) {
            return base.Channel.ObtenerCargaTrabajoProfesor(periodo);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ObtenerCargaTrabajoProfesorAsync(string periodo) {
            return base.Channel.ObtenerCargaTrabajoProfesorAsync(periodo);
        }
        
        public MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ObtenerProfesoresPorCurso(string strCodCurso) {
            return base.Channel.ObtenerProfesoresPorCurso(strCodCurso);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ObtenerProfesoresPorCursoAsync(string strCodCurso) {
            return base.Channel.ObtenerProfesoresPorCursoAsync(strCodCurso);
        }
        
        public MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[] ObtenerProfesoresPorEspecialidad(string strCodEspecialidad) {
            return base.Channel.ObtenerProfesoresPorEspecialidad(strCodEspecialidad);
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxyProfesores.ProfesorDC[]> ObtenerProfesoresPorEspecialidadAsync(string strCodEspecialidad) {
            return base.Channel.ObtenerProfesoresPorEspecialidadAsync(strCodEspecialidad);
        }
    }
}
