//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_ClienteMatricula.ProxySedes {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SedeDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class SedeDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Cod_SedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Desc_SedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UbicaciónField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantCursosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantProfesoresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int cantSeccionesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cod_Sed {
            get {
                return this.Cod_SedField;
            }
            set {
                if ((object.ReferenceEquals(this.Cod_SedField, value) != true)) {
                    this.Cod_SedField = value;
                    this.RaisePropertyChanged("Cod_Sed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Desc_Sed {
            get {
                return this.Desc_SedField;
            }
            set {
                if ((object.ReferenceEquals(this.Desc_SedField, value) != true)) {
                    this.Desc_SedField = value;
                    this.RaisePropertyChanged("Desc_Sed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ubicación {
            get {
                return this.UbicaciónField;
            }
            set {
                if ((object.ReferenceEquals(this.UbicaciónField, value) != true)) {
                    this.UbicaciónField = value;
                    this.RaisePropertyChanged("Ubicación");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantCursos {
            get {
                return this.cantCursosField;
            }
            set {
                if ((this.cantCursosField.Equals(value) != true)) {
                    this.cantCursosField = value;
                    this.RaisePropertyChanged("cantCursos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantProfesores {
            get {
                return this.cantProfesoresField;
            }
            set {
                if ((this.cantProfesoresField.Equals(value) != true)) {
                    this.cantProfesoresField = value;
                    this.RaisePropertyChanged("cantProfesores");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int cantSecciones {
            get {
                return this.cantSeccionesField;
            }
            set {
                if ((this.cantSeccionesField.Equals(value) != true)) {
                    this.cantSeccionesField = value;
                    this.RaisePropertyChanged("cantSecciones");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxySedes.IServicioSedes")]
    public interface IServicioSedes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSedes/ListarSedeConsulta", ReplyAction="http://tempuri.org/IServicioSedes/ListarSedeConsultaResponse")]
        MVC_ClienteMatricula.ProxySedes.SedeDC[] ListarSedeConsulta();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioSedes/ListarSedeConsulta", ReplyAction="http://tempuri.org/IServicioSedes/ListarSedeConsultaResponse")]
        System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySedes.SedeDC[]> ListarSedeConsultaAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioSedesChannel : MVC_ClienteMatricula.ProxySedes.IServicioSedes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioSedesClient : System.ServiceModel.ClientBase<MVC_ClienteMatricula.ProxySedes.IServicioSedes>, MVC_ClienteMatricula.ProxySedes.IServicioSedes {
        
        public ServicioSedesClient() {
        }
        
        public ServicioSedesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioSedesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSedesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioSedesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC_ClienteMatricula.ProxySedes.SedeDC[] ListarSedeConsulta() {
            return base.Channel.ListarSedeConsulta();
        }
        
        public System.Threading.Tasks.Task<MVC_ClienteMatricula.ProxySedes.SedeDC[]> ListarSedeConsultaAsync() {
            return base.Channel.ListarSedeConsultaAsync();
        }
    }
}
